name: "Release: Master"
run-name: "Release (on ${{ github.ref_name }})"

on:
  push:
    branches:
      - master

permissions:
  contents: read

env:
  IMAGE: 202797282286.dkr.ecr.eu-central-1.amazonaws.com/dpa-id-auth0-spa-demo
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read # needed for actions/checkout
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DPA_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DPA_ID }}
          aws-region: eu-central-1
      - uses: dkershner6/aws-ssm-getparameters-action@4fcb4872421f387a6c43058473acc1b22443fe13 # v2.0.3
        with:
          parameterPairs: |
            /config/dpa-id-auth0-spa-demo/auth0ClientId = VITE_AUTH0_CLIENT_ID,
            /config/dpa-id-auth0-spa-demo/auth0Domain = VITE_AUTH0_DOMAIN
      - uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      - run: |
          docker build -t ${{ env.IMAGE }}:${{ env.IMAGE_TAG }} \
            --build-arg VITE_AUTH0_DOMAIN="${{ env.VITE_AUTH0_DOMAIN }}" \
            --build-arg VITE_AUTH0_CLIENT_ID="${{ env.VITE_AUTH0_CLIENT_ID }}" \
            .
          docker push ${{ env.IMAGE }} --all-tags
  master:
    name: Master
    needs: build
    runs-on: ubuntu-latest
    env:
      STAGE: master
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DPA_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DPA_ID }}
          aws-region: eu-central-1
      - working-directory: ./infrastructure
        run: npm clean-install
      - working-directory: ./infrastructure
        run: npm run cdk deploy -- --require-approval=never dpa-id-auth0-spa-demo-master
